add apeswap banana-matic pool
harvest-finance/harvest-strategy-polygon pull request #37
Opened 2022-07-07 13:51 UTC by Crypto-One-dev

Add Apeswap MiniApev2 strategy for `banana-matic` pair
![image](https://user-images.githubusercontent.com/83286525/177788999-c285dd96-e97b-4b73-88e2-0ba00dad2564.png)

We will receive `banana` as reward from the Ape pool.

`Polygon Mainnet ApeSwap BANANA/MATIC
Impersonating...
0xf00dD244228F51547f0563e60bCa65a30FBF5f7f
Fetching Underlying at:  0x034293F21F1cCE5908BC605CE5850dF2b1059aC0
New Vault Deployed:  0x885D59830C1FdB120B54d62790dB7A6a1f534463
Strategy Deployed:  0x1caD479Dd2e9e86457594E4cEA3D4bdfE67fE373
Strategy and vault added to Controller.
farmerBalance:
2473386633013588677856
    Happy path
loop  0
old shareprice:  1000000000000000000
new shareprice:  1000000000000000000
growth:  1
loop  1
old shareprice:  1000000000000000000
new shareprice:  1000349469853992441
growth:  1.0003494698539925
loop  2
old shareprice:  1000349469853992441
new shareprice:  1000699410051572170
growth:  1.000349817946753
loop  3
old shareprice:  1000699410051572170
new shareprice:  1001049377899076040
growth:  1.0003497232475493
loop  4
old shareprice:  1001049377899076040
new shareprice:  1001399454201590828
growth:  1.0003497093252776
loop  5
old shareprice:  1001399454201590828
new shareprice:  1001749666160654332
growth:  1.0003497225383877
loop  6
old shareprice:  1001749666160654332
new shareprice:  1002099986749344665
growth:  1.0003497087151854
loop  7
old shareprice:  1002099986749344665
new shareprice:  1002450429529935037
growth:  1.0003497083975892
loop  8
old shareprice:  1002450429529935037
new shareprice:  1002800994557138840
growth:  1.000349708092168
loop  9
old shareprice:  1002800994557138840
new shareprice:  1003151695442003610
growth:  1.0003497213173584
earned!
APR: 61.364127280912825 %
APY: 84.61936270154216 %
      ✔ Farmer should earn money (182358ms)`

2022-07-08 06:09 UTC, belbix requested changes

2022-07-08 06:09 UTC, belbix commented on contracts/base/ape-base/MiniApeV2Strategy.sol
> +      IUniswapV2Router02(apeswapRouterV2).swapExactTokensForTokens(
make a test for single token or remove this logic

2022-07-08 06:09 UTC, belbix commented on contracts/base/ape-base/MiniApeV2Strategy.sol
> +  * Sets the minimum amount of CRV needed to trigger a sale.
fix comment

2022-07-08 06:09 UTC, belbix commented on contracts/base/ape-base/MiniApeV2Strategy.sol
> +  * Can completely disable claiming UNI rewards and selling. Good for emergency withdraw in the
fix comment

2022-07-08 06:09 UTC, belbix commented on contracts/base/ape-base/MiniApeV2Strategy.sol
> +    uint256 secondRewardBalance = IERC20(secondRewardToken()).balanceOf(address(this));
I think we should have sellFloor for the second reward too
please add a new variable and setter

2022-07-08 06:09 UTC, belbix commented on contracts/base/ape-base/interface/IRewarder.sol
> +    using BoringERC20 for IERC20;
remove

2022-07-08 06:09 UTC, belbix commented on contracts/base/ape-base/interface/IRewarder.sol
> +import "../lib/BoringERC20.sol";
remove

2022-07-08 06:09 UTC, belbix commented on contracts/base/ape-base/lib/BoringERC20.sol
> +library BoringERC20 {
remove, we don't need this lib

2022-07-08 08:51 UTC, belbix approved these changes

2022-07-15 01:20 UTC, CryptJS13 approved these changes
@Cryo45 @breadforthepeople Had a look at Apeswap too. It's a perfect Sushi clone. Only difference is removal of "migrator" code, which is a good thing.

It originated on BSC together with all the other Sushi clones, but somehow it survived till now. Could make decent vaults, its worth a try in my opinion.

Deployed these 7 vaults, @Crypto-One-dev will add them to the API.

2022-07-19 19:12 UTC, merged